before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  -
    binary: scgen
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags: -s -w -X main.AppVersion={{.Version}} -X main.AppBuildTime={{.Date}}
universal_binaries:
  - replace: true
    name_template: "scgen"
archives:
  - replacements:
      darwin: macOS
      amd64: x86_64
      all: universal
    name_template: "scgen_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
  disable: false
signs:
  - artifacts: checksum
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: scgen
    tap:
      owner: blacktop
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/blacktop/seccomp-gen"
    description: Docker Secure Computing Profile Generator
    install: |
      bin.install "scgen"
    test: |
      system "#{bin}/scgen --version"
rigs:
  - name: scgen
    rig:
      owner: blacktop
      name: fish-food
    homepage: https://github.com/blacktop/seccomp-gen
    description: Docker Secure Computing Profile Generator
    license: MIT
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^bumping"
      - "^Update"
      - "reorg"
      - "updates"
      - Merge pull request
      - Merge branch
release:
  footer: |
    ## What to do next?
    - Follow us on [Twitter](https://twitter.com/blacktop__);
