# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
builds:
  - binary: ipsw
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags: -s -w -X main.AppVersion={{.Version}} -X main.AppBuildTime={{.Date}}

archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: amd64
    darwin: macOS
    linux: linux
    windows: win

brew:
  github:
    owner: blacktop
    name: homebrew-tap
  folder: Formula
  homepage: "https://github.com/blacktop/ipsw"
  description: "Download ipsw(s) from ipsw.me or theiphonewiki.com"
  test: |
    system "#{bin}/ipsw --version"

checksum:
  name_template: "checksums.txt"

sign:
  artifacts: checksum

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "update README"
